---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
spec:
  chartRef:
    kind: OCIRepository
    name: garage
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      garage:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: dxflrs/garage
              tag: v2.3.0
            args:
              - /garage
              - server
              - --single-node
              - --default-bucket
            envFrom:
              - secretRef:
                  name: garage-secret
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                cpu: 50m
                memory: 1Gi
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
              readOnlyRootFilesystem: false
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
        statefulset:
          volumeClaimTemplates:
            - name: data
              accessMode: ReadWriteOnce
              size: 20Gi
              storageClass: ceph-block
              globalMounts:
                - path: /var/lib/garage

    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: garage
        ports:
          s3:
            port: 3900
          admin:
            port: 3903

    persistence:
      config:
        type: configMap
        name: garage-config
        globalMounts:
          - path: /etc/garage.toml
            subPath: garage.toml
            readOnly: true
