---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hindsight
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hindsight-secret
    template:
      engineVersion: v2
      data:
        HINDSIGHT_API_DATABASE_URL: "postgresql://hindsight:{{ .POSTGRES_PASSWORD }}@postgres17-rw.database.svc.cluster.local:5432/hindsight"
        HINDSIGHT_API_LLM_API_KEY: "{{ .OPENROUTER_API_KEY }}"
        HINDSIGHT_API_TENANT_API_KEY: "{{ .HINDSIGHT_API_KEY }}"
        HINDSIGHT_CP_DATAPLANE_API_KEY: "{{ .HINDSIGHT_API_KEY }}"
        HINDSIGHT_CP_ACCESS_KEY: "{{ .HINDSIGHT_CP_ACCESS_KEY }}"
        INIT_POSTGRES_DBNAME: hindsight
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: hindsight
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: hindsight
    - extract:
        key: cloudnative-pg
