---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cosa2-obsidian
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cosa2-obsidian-secret
    template:
      engineVersion: v2
      data:
        OBSIDIAN_AUTH_TOKEN: "{{ .OBSIDIAN_AUTH_TOKEN }}"
        OBSIDIAN_VAULT: "{{ .OBSIDIAN_VAULT }}"
        OBSIDIAN_VAULT_PASSWORD: "{{ .OBSIDIAN_VAULT_PASSWORD }}"
  dataFrom:
    - extract:
        key: cosa2
