---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name openclaw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      data:
        ## Gateway token for authentication
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        ##Discord
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        ## GH Access
        # GITHUB_APP_CLIENT_ID: "{{ .GH_BOT_CLIENT_ID }}"
        # GITHUB_APP_CLIENT_SECRET: "{{ .GH_BOT_CLIENT_SECRET }}"
        # GITHUB_APP_ID: "{{ .GH_BOT_ID }}"
        # GITHUB_APP_INSTALLATION_ID: "{{ .GH_BOT_INSTALLATION_ID }}"
        # GITHUB_APP_PRIVATE_KEY: "{{ .GH_BOT_PRIVATE_KEY }}"
        # GH_PAT: "{{ .GH_BOT_PAT }}"
        ## API Keys
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        GOOGLE_AI_STUDIO_API_KEY: "{{ .GOOGLE_GEMINI_API_KEY }}"
        MISTRAL_API_KEY: "{{ .MISTRAL_API_KEY }}"
        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
        ## HASS
        HA_URL: "https://hass.mcgrath.nz"
        HA_TOKEN: "{{ .HOME_ASSISTANT_TOKEN }}"
        ## Dashclaw
        # DASHCLAW_API_KEY: "{{ .DASHCLAW_API_KEY }}"
        # DASHCLAW_BASE_URL: https://dashclaw.mcgrath.nz
        ## Connections
        #OPENCLAW_PHONE_NUMBER: "{{ .OPENCLAW_PHONE_NUMBER }}"
        #WHATSAPP_PHONE_NUMBER: "{{ .WHATSAPP_PHONE_NUMBER }}"
        GOG_KEYRING_PASSWORD: "{{ .GOG_KEYRING_PASSWORD }}"
        GH_TOKEN: "{{ .GH_TOKEN }}"
        OP_SERVICE_ACCOUNT_TOKEN: "{{ .OP_SERVICE_ACCOUNT_TOKEN }}"
  dataFrom:
    - extract:
        key: openclaw
        nullBytePolicy: Ignore
    # - extract:
    #     key: dashclaw
