---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snmp-exporter-synology
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: snmp-exporter-synology
    template:
      engineVersion: v2
      data:
        snmp-auth.yml: |
          auths:
            synology_v3:
              version: 3
              security_level: authPriv
              username: "{{ .SNMP_USERNAME }}"
              password: "{{ .SNMP_AUTH_PASSWORD }}"
              auth_protocol: SHA
              priv_protocol: AES
              priv_password: "{{ .SNMP_PRIV_PASSWORD }}"
  dataFrom:
    - extract:
        key: snmp-exporter-synology
