---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: synology-dashboard
    files:
      - synology-dashboard.json=./resources/dashboard.json
  - name: synology-snmp-metadata
    files:
      - snmp-metadata.yml=./resources/snmp-metadata.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
