apiVersion: v1
kind: Secret
metadata:
    name: cosa-secret
type: Opaque
stringData:
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:mXFmLFzwdYpcesw9lgHNhl7vLvC6/3krjLkpmzRNbeyvJlpDQg3ZCnCIk+J9xqu8+LeA4/kRRtqYOVhUsCzmqy0KsGvS5coxmF0ZHB7kGr9B12iSGVmNJpEAodMV1XHHfMJMvPkhMML/OOj/,iv:ZSav0J97mDVP0/tMj++nPYRW/35WJw7Arzfl0xpi1yo=,tag:0KWDQyvVfn2zW+s5OHksNQ==,type:str]
    COSA_DAILY_FILENAME: ENC[AES256_GCM,data:j3RT6k9Uru5gk83W1A4=,iv:UkOlAB9Rr7aPRww6NNdsqsGSVnUaRg2vQBdkB9j0rG4=,tag:Ir96U0an+9AMyiY1ytuFjw==,type:str]
    COSA_DAILY_FOLDER: ENC[AES256_GCM,data:oS+5fNaz5tn3VjE5cei49WkHUZT2SJ7HwNRd5YBkW8A+wQNhhA==,iv:SG1wX3DDykutN/Ep2jvg21RdWxObdM3oAoyFan4xhWM=,tag:k64CaTrpolkQkEX3WR32/g==,type:str]
    COSA_DAILY_TEMPLATE_PATH: ENC[AES256_GCM,data:S596l4UN3me8NPk9MfmtIocybILfwE0CtHGk,iv:610pgEMMLhG1jj+1U2BsHzzAfjPWtUoZGlt+GlG8HX0=,tag:612w9UJldR8KlzyBpwC35g==,type:str]
    COSA_GITHUB_TOKEN: ENC[AES256_GCM,data:DP7U59nhEuPtsxq7dHha5yWsM/w7W/Fwx84bqbd9tcuMKHGm7Dpxnw==,iv:I+bQaWeP2XMrkhYm1UlPdp0v+Uxsnw4DVRceowuvVuU=,tag:kqS/BjMAK5TLl8ORBnav1Q==,type:str]
    COSA_HINDSIGHT_API_KEY: ENC[AES256_GCM,data:C8qnRe8Cm2QLeFXMIayn/vv4dFTN95trYJ4I/2Z3vOU=,iv:YmhKRHyapKfAnoj5F1h82CvcG+xOFoov6XPjoguOsFc=,tag:SVzJ0pjtq6oMdeppLh1iOw==,type:str]
    COSA_HINDSIGHT_URL: ENC[AES256_GCM,data:Mdr0WMwK+5FvVMygbrM3sG5bczGZww==,iv:Y80lPlkY7VpfxV0AQyYwnIE46xr3Pr0hu3Bru99Evo4=,tag:uSlwxV2N/463RZTe8WC+MQ==,type:str]
    COSA_MCP_TOKEN: ENC[AES256_GCM,data:gu/M8a0s7iY4pKbkfjkt+R64v90Juxdakl4x0adZ/ENe7NYcq+RGzP64zw==,iv:hSN7cBLDS+nBtRuqUoqtbz4UMecAcTIayLFyOoNh+Vs=,tag:lFQjoDuscUKSj9nkQIssWg==,type:str]
    COSA_PI_MODELS: ENC[AES256_GCM,data:kVYLx7TM/RtGvm/p3To1ep8q6tBmEd1PwIV2LMjS8WIgsNCrEZTM3PoV9/0u/E94kDoO0PlmNb4AQtiZu5Wp7mapCgUa2i+xG7wWg/sykinKp/W6MOLiPg8akNCTtS1mw+cc9EIDoYIxCpjaYLHlUnMDooqat248U2MmzaYmHLYdG+uBoWy2JkPj7k3YmDaEbjUBip2hNDiWCuOXAetdr6bMisUmzRTHvTMFAMIlFmsG9us=,iv:tKnoWP4u3p2Ui0T9cfNKjxosVlVSFooqjSBuGTmjaac=,tag:Q4RqT8Pi9Gp+8Gql399Kkg==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:5maNdUnoVXtRaP2mhHVNxRIsM3MeS2rSXg==,iv:vcRvIVpDIUx0L3UNweQf9GVg68hQ/jbXEGk0HUCm+Ns=,tag:3u6jcqcn3uHekPh5ZZKHIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOEsyYkIrS2xxUEIwbDdP
            U1pqZ0VKazFiK1dMNFN6MVR5VTJPdGEzVXlBCjI1elZ6YXQyTGVGakxiS2tYVjlF
            S1k4eFBncEYzQmJoYXVJMEJReklwVHMKLS0tIEtaM2J0UWx1dXhsUGs3dGVGVEtX
            UUxrUEZKTDZUemNPNnVBZ3FxNHQrZmsKXwH5eFVejWDHBYHkzr1qKqhW3MvmGBCs
            j7ib/UWqtznppp1vuOadYq+XlIERlP/eHKUKePiN90L+Y89SGesZdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gvxhazdcrf83u2mhvat4le39eaw0gr5vg3eqj4nz444umzem6gcq6493xw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T10:52:48Z"
    mac: ENC[AES256_GCM,data:7GcHPlQ7SIZ3IWYe9ngKZCJYHhlCo0lQP7l2mAA12K3MfAIHe3WrCyTFfz7c0z5Bg8mLMExbnc8zEL14mEoCt+Wse7nVIrU61zGWnL8F8F0lBwZXntatXB7mefrp+pn+psYDIN+X7xGObOCCkfBT8niD1sfCJGm3j+7jEEFafwk=,iv:/8YG3592cmsRN9WFnWNihHtOmCRFNco9fUACW+ew1T4=,tag:1ec7zH2c/+dFqHMoDBQzCw==,type:str]
    version: 3.13.3
