---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hermes-secret
    template:
      engineVersion: v2
      data:
        API_SERVER_KEY: "{{ .API_SERVER_KEY }}"

        LITELLM_API_KEY: "{{ .LITELLM_API_KEY }}"
        LITELLM_BASE_URL: "{{ .LITELLM_BASE_URL }}"

        GH_TOKEN: "{{ .GITHUB_TOKEN }}"

        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        DISCORD_ALLOWED_USERS: "{{ .DISCORD_ALLOWED_USERS }}"
        DISCORD_HOME_CHANNEL: "{{ .DISCORD_HOME_CHANNEL }}"
        DISCORD_HOME_CHANNEL_NAME: Bingle

        HASS_TOKEN: "{{ .HOME_ASSISTANT_TOKEN }}"
        HASS_URL: "http://home-assistant.default.svc.cluster.local:8123"

  dataFrom:
    - extract:
        key: hermes
