---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hermes-secret
    template:
      engineVersion: v2
      data:
        LITELLM_API_KEY: "{{ .LITELLM_API_KEY }}"
        LITELLM_BASE_URL: "{{ .LITELLM_BASE_URL }}"
        GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        HOME_ASSISTANT_TOKEN: "{{ .HOME_ASSISTANT_TOKEN }}"

  dataFrom:
    - extract:
        key: hermes
