---
ingress:
  - hostname: "*.mcgrath.nz"
    originRequest:
      http2Origin: true
      originServerName: external.mcgrath.nz
    service: https://envoy-external.networking.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN_2}"
    originRequest:
      http2Origin: true
      originServerName: external.mcgrath.nz
    service: https://envoy-external.networking.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN_3}"
    originRequest:
      http2Origin: true
      originServerName: external.mcgrath.nz
    service: https://envoy-external.networking.svc.cluster.local:443
  - hostname: "${SECRET_GHOST_DOMAIN}"
    originRequest:
      http2Origin: true
      originServerName: external.mcgrath.nz
    service: https://envoy-external.networking.svc.cluster.local:443
  - hostname: "${SECRET_WP_0_DOMAIN}"
    originRequest:
      http2Origin: true
      originServerName: external.mcgrath.nz
    service: https://envoy-external.networking.svc.cluster.local:443
  - hostname: "www.${SECRET_WP_0_DOMAIN}"
    originRequest:
      http2Origin: true
      originServerName: external.mcgrath.nz
    service: https://envoy-external.networking.svc.cluster.local:443
  - hostname: "${SECRET_DOMAIN_SPARKLE}"
    originRequest:
      http2Origin: true
      originServerName: external.mcgrath.nz
    service: https://envoy-external.networking.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN_SPARKLE}"
    originRequest:
      http2Origin: true
      originServerName: external.mcgrath.nz
    service: https://envoy-external.networking.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN_HARVCO}"
    originRequest:
      http2Origin: true
      originServerName: external.mcgrath.nz
    service: https://envoy-external.networking.svc.cluster.local:443
  - service: http_status:404
