---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snapotter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: snapotter-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://snapotter:{{ .POSTGRES_PASSWORD }}@postgres17-rw.database.svc.cluster.local:5432/snapotter"

        # Postgres Init
        INIT_POSTGRES_DBNAME: snapotter
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: snapotter
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: snapotter
