---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapotter
spec:
  chartRef:
    kind: OCIRepository
    name: snapotter
  interval: 1h
  values:
    controllers:
      snapotter:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18
            envFrom: &envFrom
              - secretRef:
                  name: snapotter-secret

        containers:
          app:
            image:
              repository: ghcr.io/snapotter-hq/snapotter
              tag: 2.1.0@sha256:cb2c8835bc0939adcf8054570f9a116f24437626c2dba9f66206f4ed86f79809
            env:
              TZ: Pacific/Auckland
              PORT: &port 1349
              AUTH_ENABLED: true
              ANALYTICS_ENABLED: false
              REDIS_URL: redis://dragonfly.database.svc.cluster.local:6379/8
            envFrom: *envFrom
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: snapotter
        ports:
          http:
            port: *port

    route:
      app:
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
        hostnames:
          - snap.mcgrath.nz
        rules:
          - backendRefs:
              - identifier: app
                port: http

    persistence:
      data:
        existingClaim: snapotter-data
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
