---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sure
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sure-secret
    template:
      engineVersion: v2
      data:
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"

        # Postgres connection
        POSTGRES_DB: &dbName sure
        POSTGRES_USER: &dbUser "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .POSTGRES_PASS }}"
        DB_HOST: &dbHost postgres17-rw.database.svc.cluster.local
        DB_PORT: "5432"

        # Init container vars
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: sure
    - extract:
        key: cloudnative-pg
