---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
patches:
  - target:
      kind: Replication(Source|Destination)
    patch: |-
      - op: replace
        path: /spec/restic/storageClassName
        value: synology-iscsi-ephemeral
  - target:
      kind: ReplicationDestination
    patch: |-
      - op: replace
        path: /spec/restic/cleanupTempPVC
        value: false
