---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: client-info-secret
    template:
      engineVersion: v2
      data:
        client-info.yml: |-
          clients:
            - host: 10.0.16.16
              port: 5001
              https: true
              username: {{ .username | toJson }}
              password: {{ .confirmpassword | toJson }}
              tlsServerName: synology
              tlsCACert: |
                -----BEGIN CERTIFICATE-----
                MIID8jCCAtqgAwIBAgIHFoASZEaXXjANBgkqhkiG9w0BAQsFADBRMQswCQYDVQQG
                EwJUVzEPMA0GA1UEBwwGVGFpcGVsMRYwFAYDVQQKDA1TeW5vbG9neSBJbmMuMRkw
                FwYDVQQDDBBTeW5vbG9neSBJbmMuIENBMB4XDTI2MDgyMjA2NDgyNVoXDTI3MDgy
                MzA2NDgyNVowSTELMAkGA1UEBhMCVFcxDzANBgNVBAcMBlRhaXBlbDEWMBQGA1UE
                CgwNU3lub2xvZ3kgSW5jLjERMA8GA1UEAwwIc3lub2xvZ3kwggEiMA0GCSqGSIb3
                DQEBAQUAA4IBDwAwggEKAoIBAQChUeBc0omlyFars29cbt+ddD4e7qYNYGu7Al4R
                40C/a8h4f3cKl//hbCA81uE3K74Ru1xZhkyU/RjjQvrK3EzCCsfgE9QYnHRr+vLS
                qOHld6BTYivfuQXuvqobrHSJZ3toynwdwrBcHvkgILDONqxh8MUeYFo8S08BepAC
                d8K59LK5oAJH788yhgf3BamiLnSv8CllZJ5pKYLoQSCy37UPeMGRqaUGc/xLWTpt
                8MSpbbvkCqXyDM81MH1u9FD5D66w+QheUDMgWaMK4Eh4hA5TU3l+wDW47ZBMD/Rt
                Tuu+aRpcwjv5SeEtJDxCmXWBlVaaxRnxIbzeZMVGE9sTnNeJAgMBAAGjgdYwgdMw
                OgYJYIZIAYb4QgENBC0WK21vZF9zc2wgZ2VuZXJhdGVkIGN1c3RvbSBzZXJ2ZXIg
                Y2VydGlmaWNhdGUwEQYJYIZIAYb4QgEBBAQDAgZAMA4GA1UdDwEB/wQEAwIFoDAd
                BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwEwYDVR0RBAwwCoIIc3lub2xv
                Z3kwHQYDVR0OBBYEFGgxJToTP5XszpV9/D/Y9CTKsPzJMB8GA1UdIwQYMBaAFLkk
                nxTUcEk9HhLMWey+KtDONXz+MA0GCSqGSIb3DQEBCwUAA4IBAQA6yfeipG3D1hOz
                TxFO2Th7dH2qHPGBS2G8Jk7oDh1R4BuEtfHf791p9t39kpkHt8pR7S4PZVSFRN5s
                zGNcvvQ4Jr9uA8MEEqtcMfbZlMdrKZDlS5e16gTLEy+AD1iK0wu9F/alPAG3EyzL
                APXXXM6vBAPvSBg+PBblRb3Nefneh8R2hJsjwEDVp4OAcd9CJBapFyqadp1F4ua6
                jQMxBkWFJL9KFBjnGA2Wes5w3s36Y+IWBEInf2o1bAsOgAghJQu4pebFQqCChPAD
                tmEc6e9ENZ75xvc/4vX1736LMg3VjQLXtnuERQ4TI7034I2h41WIGMnFqu0UwBgG
                xyGUWpA7
                -----END CERTIFICATE-----
  dataFrom:
    - extract:
        key: synology-csi
