---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tailscale-router-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        TS_AUTHKEY: "{{ .auth_key }}"
  dataFrom:
    - extract:
        key: headscale-router
