---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app librechat
  namespace: default
spec:
  targetNamespace: default
  dependsOn:
    - name: external-secrets-stores
      namespace: kube-system
  path: ./kubernetes/apps/default/librechat/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_LOCAL_SCHEDULE: "43 * * * *"
  components:
    - ../../../../components/volsync

---

# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app garage
  namespace: default
spec:
  targetNamespace: default
  dependsOn:
    - name: external-secrets-stores
      namespace: kube-system
  path: ./kubernetes/apps/default/librechat/garage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app

---

# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app code-interpreter
  namespace: default
spec:
  targetNamespace: default
  dependsOn:
    - name: external-secrets-stores
      namespace: kube-system
    - name: garage
      namespace: default
  path: ./kubernetes/apps/default/librechat/code-interpreter
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app

---

# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app librechat-admin
  namespace: default
spec:
  targetNamespace: default
  dependsOn:
    - name: external-secrets-stores
      namespace: kube-system
    - name: librechat
      namespace: default
  path: ./kubernetes/apps/default/librechat/librechat-admin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
