---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cdi
components:
  - ../../components/common
resources:
  - ./operator/ks.yaml
  - ./control-plane/ks.yaml
patches:
  - target:
      kind: Namespace
      name: not-used
    patch: |-
      - op: add
        path: /metadata/labels/cdi.kubevirt.io
        value: ""
