---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.98.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  values:
    operatorConfig:
      hostname: tailscale-operator
      image:
        repository: ghcr.io/tailscale/k8s-operator
        tag: v1.98.3@sha256:a3f3bcb653ce85e36ae4df49708bcb194d3f7b41d098655becc480d9d003b3cd
    proxyConfig:
      image:
        repository: ghcr.io/tailscale/tailscale
        tag: v1.98.4@sha256:25cde9ad76020b0e29229136d0c38b5962e9a0e1774ffac9b0df68e4a37d6cf0
    apiServerProxyConfig:
      mode: noauth
