---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: tailscale-operator
  values:
    operatorConfig:
      hostname: tailscale-operator
      image:
        repository: ghcr.io/tailscale/k8s-operator
        tag: v1.98.4@sha256:59060effe5baeeac7909f23871549fbbd9da78dd5b03af8c89bccb35ba46e93c
    proxyConfig:
      image:
        repository: ghcr.io/tailscale/tailscale
        tag: v1.98.8@sha256:d54b2e6a9c09f0e5ec52e82b9ad4af3d446b54a7c08075e92f11c39dd410105f
    apiServerProxyConfig:
      mode: noauth
