---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: dev-vm-r2
spec:
  sourcePVC: dev-vm-root
  trigger:
    schedule: "30 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: dev-vm-volsync-r2-secret
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 2Gi
    cacheStorageClassName: ceph-block
    cacheAccessModes:
      - ReadWriteOnce
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: OnRootMismatch
    retain:
      daily: 7
