---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cdi
  namespace: cdi
spec:
  dependsOn:
    - name: cdi-operator
      namespace: cdi
  healthCheckExprs:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: CDI
      current: status.conditions.exists(c, c.type == 'Available' && c.status == 'True')
  healthChecks:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: CDI
      name: cdi
  interval: 30m
  path: ./kubernetes/apps/cdi/control-plane/app
  prune: false
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 15m
  wait: true
