---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux-rules
  namespace: flux-system
spec:
  groups:
    - name: flux.rules
      rules:
        - alert: FluxComponentAbsent
          annotations:
            summary: Flux component has disappeared from Prometheus target discovery.
          expr: |
            absent(up{job=~".*flux-system.*"} == 1)
          for: 15m
          labels:
            severity: critical
        - alert: HelmReleaseReconciliationFailure
          annotations:
            summary: >-
              HelmRelease {{ $labels.name }} in {{ $labels.exported_namespace }} is not ready
          expr: |
            gotk_resource_info{customresource_kind="HelmRelease", ready!="True"} == 1
          for: 15m
          labels:
            severity: critical
        - alert: KustomizationReconciliationFailure
          annotations:
            summary: >-
              Kustomization {{ $labels.name }} in {{ $labels.exported_namespace }} is not ready
          expr: |
            gotk_resource_info{customresource_kind="Kustomization", ready!="True"} == 1
          for: 15m
          labels:
            severity: critical
